<Project>
  <PropertyGroup>
    <LangVersion>Latest</LangVersion>
    <Copyright>Ilya Belyanskiy 2022</Copyright>
    <Authors>Belyanskiy Ilya</Authors>
    <PackageProjectUrl>https://laraue.com/blog/articles/ollama-dotnet</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Laraue/Laraue.Ollama.NET</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <!-- Designate all projects as non-package projects by default -->
    <IsPackable>false</IsPackable>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
  
  <PropertyGroup>
    <MicrosoftPackagesVersion>[10.0.0, 11)</MicrosoftPackagesVersion>
  </PropertyGroup>
</Project>