name: Build and publish package
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # required so the job can request a GitHub OIDC token

    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Setup .NET environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '10.x.x'

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run unit tests
        run: dotnet test --filter 'Category!=IntegrationTest'

      - name: Generate a NuGet package
        run: dotnet pack --no-build -c Release -o .

      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: win7user10

      - name: Push to NuGet.org
        run: dotnet nuget push "*.nupkg" --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate